syntax = "proto3";

package anthropic.bard.api.v1alpha;

enum BuiltinIconType {
  BUILTIN_ICON_TYPE_UNSPECIFIED = 0;
  BUILTIN_ICON_TYPE_WRENCH = 1;
  BUILTIN_ICON_TYPE_FILE = 2;
  BUILTIN_ICON_TYPE_FOLDER = 3;
  BUILTIN_ICON_TYPE_EDIT = 4;
  BUILTIN_ICON_TYPE_SEARCH = 5;
  BUILTIN_ICON_TYPE_GLOBE = 6;
  BUILTIN_ICON_TYPE_CODE = 7;
  BUILTIN_ICON_TYPE_COMMAND_LINE_PROMPT = 8;
  BUILTIN_ICON_TYPE_EMAIL = 9;
  BUILTIN_ICON_TYPE_CHAT = 10;
  BUILTIN_ICON_TYPE_CALENDAR = 11;
  BUILTIN_ICON_TYPE_CLOCK = 12;
  BUILTIN_ICON_TYPE_NOTIFICATION = 13;
  BUILTIN_ICON_TYPE_IMAGE = 14;
  BUILTIN_ICON_TYPE_CAMERA = 15;
  BUILTIN_ICON_TYPE_MAP_PIN = 16;
  BUILTIN_ICON_TYPE_DATABASE = 17;
  BUILTIN_ICON_TYPE_CHART = 18;
  BUILTIN_ICON_TYPE_SPARKLE = 19;
  BUILTIN_ICON_TYPE_LIGHTBULB = 20;
  BUILTIN_ICON_TYPE_DOWNLOAD = 21;
  BUILTIN_ICON_TYPE_UPLOAD = 22;
  BUILTIN_ICON_TYPE_SHARE = 23;
  BUILTIN_ICON_TYPE_LINK = 24;
  BUILTIN_ICON_TYPE_LOCK = 25;
  BUILTIN_ICON_TYPE_ACTIVITY = 1000;
  BUILTIN_ICON_TYPE_ADD = 1001;
  BUILTIN_ICON_TYPE_ADD_CIRCLE = 1002;
  BUILTIN_ICON_TYPE_AGENT = 1003;
  BUILTIN_ICON_TYPE_ALARM = 1004;
  BUILTIN_ICON_TYPE_ANDROID = 1005;
  BUILTIN_ICON_TYPE_ANT = 1006;
  BUILTIN_ICON_TYPE_APPLE = 1007;
  BUILTIN_ICON_TYPE_ARCHIVE = 1008;
  BUILTIN_ICON_TYPE_ARROW_DOWN = 1009;
  BUILTIN_ICON_TYPE_ARROW_DOWN_CIRCLE = 1010;
  BUILTIN_ICON_TYPE_ARROW_IN_SQUARE = 1011;
  BUILTIN_ICON_TYPE_ARROW_LEFT = 1012;
  BUILTIN_ICON_TYPE_ARROW_LEFT_CIRCLE = 1013;
  BUILTIN_ICON_TYPE_ARROW_OUT_SQUARE = 1014;
  BUILTIN_ICON_TYPE_ARROW_RETURN = 1015;
  BUILTIN_ICON_TYPE_ARROW_RIGHT = 1016;
  BUILTIN_ICON_TYPE_ARROW_RIGHT_CIRCLE = 1017;
  BUILTIN_ICON_TYPE_ARROW_SPLIT_RIGHT = 1018;
  BUILTIN_ICON_TYPE_ARROW_UP = 1019;
  BUILTIN_ICON_TYPE_ARROW_UP_CIRCLE = 1020;
  BUILTIN_ICON_TYPE_ARROW_UP_RIGHT = 1021;
  BUILTIN_ICON_TYPE_ARROWS_OUT = 1022;
  BUILTIN_ICON_TYPE_ARTIFACTS = 1023;
  BUILTIN_ICON_TYPE_ATOM = 1024;
  BUILTIN_ICON_TYPE_ATTACHMENT = 1025;
  BUILTIN_ICON_TYPE_BATCH = 1026;
  BUILTIN_ICON_TYPE_BEAKER = 1027;
  BUILTIN_ICON_TYPE_BINOCULARS = 1028;
  BUILTIN_ICON_TYPE_BOOK = 1029;
  BUILTIN_ICON_TYPE_BOOK_CLOSED = 1030;
  BUILTIN_ICON_TYPE_BOOK_TEXT = 1031;
  BUILTIN_ICON_TYPE_BOX = 1032;
  BUILTIN_ICON_TYPE_BROWSE_SELECT = 1033;
  BUILTIN_ICON_TYPE_BULLHORN = 1034;
  BUILTIN_ICON_TYPE_CACHE = 1035;
  BUILTIN_ICON_TYPE_CAPACITY = 1038;
  BUILTIN_ICON_TYPE_CARET_DOWN = 1039;
  BUILTIN_ICON_TYPE_CARET_DOWN_UP = 1040;
  BUILTIN_ICON_TYPE_CARET_LEFT = 1041;
  BUILTIN_ICON_TYPE_CARET_RIGHT = 1042;
  BUILTIN_ICON_TYPE_CARET_UP = 1043;
  BUILTIN_ICON_TYPE_CARET_UP_DOWN = 1044;
  BUILTIN_ICON_TYPE_CHANGES_PLUS_MINUS = 1045;
  BUILTIN_ICON_TYPE_CHANGES_PLUS_MINUS_FILLED = 1046;
  BUILTIN_ICON_TYPE_CHART_LINE = 1048;
  BUILTIN_ICON_TYPE_CHAT_ADD = 1050;
  BUILTIN_ICON_TYPE_CHAT_ADD_FILLED = 1051;
  BUILTIN_ICON_TYPE_CHAT_DELETE = 1052;
  BUILTIN_ICON_TYPE_CHAT_DELETE_FILLED = 1053;
  BUILTIN_ICON_TYPE_CHAT_FILLED = 1054;
  BUILTIN_ICON_TYPE_CHAT_SIMPLE = 1055;
  BUILTIN_ICON_TYPE_CHAT_SIMPLE_FILLED = 1056;
  BUILTIN_ICON_TYPE_CHATS = 1057;
  BUILTIN_ICON_TYPE_CHATS_FILLED = 1058;
  BUILTIN_ICON_TYPE_CHECK = 1059;
  BUILTIN_ICON_TYPE_CHECK_CIRCLE = 1060;
  BUILTIN_ICON_TYPE_CHECK_CIRCLE_FILLED = 1061;
  BUILTIN_ICON_TYPE_CHECK_DOUBLE = 1062;
  BUILTIN_ICON_TYPE_CHECKLIST = 1063;
  BUILTIN_ICON_TYPE_CHECKLIST_FILLED = 1064;
  BUILTIN_ICON_TYPE_CLIPBOARD = 1065;
  BUILTIN_ICON_TYPE_CLIPBOARD_ARROW = 1066;
  BUILTIN_ICON_TYPE_CLOUD = 1068;
  BUILTIN_ICON_TYPE_CLOUD_FILLED = 1069;
  BUILTIN_ICON_TYPE_CLOUD_SLASH = 1070;
  BUILTIN_ICON_TYPE_CLOUD_SLASH_FILLED = 1071;
  BUILTIN_ICON_TYPE_CODE_BLOCK = 1073;
  BUILTIN_ICON_TYPE_CODE_BRACKETS = 1074;
  BUILTIN_ICON_TYPE_CODE_FILLED = 1075;
  BUILTIN_ICON_TYPE_COFFEE_CUP = 1076;
  BUILTIN_ICON_TYPE_COLLAPSE = 1077;
  BUILTIN_ICON_TYPE_COMMAND_CARD = 1078;
  BUILTIN_ICON_TYPE_COMMAND_LINE = 1079;
  BUILTIN_ICON_TYPE_COMMAND_LINE_FILLED = 1080;
  BUILTIN_ICON_TYPE_COMPACT = 1082;
  BUILTIN_ICON_TYPE_COMPUTER = 1083;
  BUILTIN_ICON_TYPE_CONCIERGE = 1084;
  BUILTIN_ICON_TYPE_CONNECTORS = 1085;
  BUILTIN_ICON_TYPE_COPY = 1086;
  BUILTIN_ICON_TYPE_CREATE = 1087;
  BUILTIN_ICON_TYPE_CREDIT_CARD = 1088;
  BUILTIN_ICON_TYPE_CURSOR = 1089;
  BUILTIN_ICON_TYPE_CURSOR_FILLED = 1090;
  BUILTIN_ICON_TYPE_DNA = 1091;
  BUILTIN_ICON_TYPE_DISCONNECT = 1093;
  BUILTIN_ICON_TYPE_DISPATCH = 1094;
  BUILTIN_ICON_TYPE_DOLLAR_SIGN = 1095;
  BUILTIN_ICON_TYPE_DOTS_CIRCLE = 1096;
  BUILTIN_ICON_TYPE_DOTS_HORIZONTAL = 1097;
  BUILTIN_ICON_TYPE_DOTS_VERTICAL = 1098;
  BUILTIN_ICON_TYPE_EVALS = 1102;
  BUILTIN_ICON_TYPE_EXPAND = 1103;
  BUILTIN_ICON_TYPE_EXTENDED_THINKING = 1104;
  BUILTIN_ICON_TYPE_EYE = 1105;
  BUILTIN_ICON_TYPE_EYE_SLASH = 1106;
  BUILTIN_ICON_TYPE_FASTFORWARD = 1107;
  BUILTIN_ICON_TYPE_FILE_ADD = 1109;
  BUILTIN_ICON_TYPE_FILE_UPLOAD = 1110;
  BUILTIN_ICON_TYPE_FILES = 1111;
  BUILTIN_ICON_TYPE_FILTER = 1112;
  BUILTIN_ICON_TYPE_FLAG = 1113;
  BUILTIN_ICON_TYPE_FOLDER_OPEN = 1115;
  BUILTIN_ICON_TYPE_FOLDER_PLUS = 1116;
  BUILTIN_ICON_TYPE_GHOST = 1117;
  BUILTIN_ICON_TYPE_GHOST_FILLED = 1118;
  BUILTIN_ICON_TYPE_GIFT = 1119;
  BUILTIN_ICON_TYPE_GIT_BRANCH = 1120;
  BUILTIN_ICON_TYPE_GIT_COMMIT = 1121;
  BUILTIN_ICON_TYPE_GIT_DIFF = 1122;
  BUILTIN_ICON_TYPE_GIT_FORK = 1123;
  BUILTIN_ICON_TYPE_GIT_MERGE = 1124;
  BUILTIN_ICON_TYPE_GIT_MERGE_CONFLICT = 1125;
  BUILTIN_ICON_TYPE_GIT_MERGED_SIMPLE = 1126;
  BUILTIN_ICON_TYPE_GIT_PULL_REQUEST = 1127;
  BUILTIN_ICON_TYPE_GIT_PULL_REQUEST_CLOSED = 1128;
  BUILTIN_ICON_TYPE_GIT_PULL_REQUEST_DRAFT = 1129;
  BUILTIN_ICON_TYPE_GRADUATION_CAP = 1131;
  BUILTIN_ICON_TYPE_GRID = 1132;
  BUILTIN_ICON_TYPE_HAND = 1133;
  BUILTIN_ICON_TYPE_HAND_HEART = 1134;
  BUILTIN_ICON_TYPE_HAPTICS = 1135;
  BUILTIN_ICON_TYPE_HELP = 1136;
  BUILTIN_ICON_TYPE_HISTORY = 1137;
  BUILTIN_ICON_TYPE_HOME = 1138;
  BUILTIN_ICON_TYPE_ID = 1139;
  BUILTIN_ICON_TYPE_INDENT = 1141;
  BUILTIN_ICON_TYPE_INFO_SIMPLE = 1142;
  BUILTIN_ICON_TYPE_INFO = 1143;
  BUILTIN_ICON_TYPE_INTERACTIVE = 1144;
  BUILTIN_ICON_TYPE_KEY = 1145;
  BUILTIN_ICON_TYPE_KEYBOARD = 1146;
  BUILTIN_ICON_TYPE_LAPTOP = 1147;
  BUILTIN_ICON_TYPE_LAPTOP_FILLED = 1148;
  BUILTIN_ICON_TYPE_LAPTOP_SLASH = 1149;
  BUILTIN_ICON_TYPE_LIBRARY = 1150;
  BUILTIN_ICON_TYPE_LIGHTNING = 1152;
  BUILTIN_ICON_TYPE_LINK_SIMPLE = 1154;
  BUILTIN_ICON_TYPE_LIST_ADD = 1155;
  BUILTIN_ICON_TYPE_LIST_BULLET = 1156;
  BUILTIN_ICON_TYPE_LIST_NUMBERED = 1157;
  BUILTIN_ICON_TYPE_LOCATION = 1158;
  BUILTIN_ICON_TYPE_LOCATION_QUESTION_MARK = 1159;
  BUILTIN_ICON_TYPE_LOCATION_SLASH = 1160;
  BUILTIN_ICON_TYPE_LOCK_OPEN = 1162;
  BUILTIN_ICON_TYPE_LOCK_SHIELD = 1163;
  BUILTIN_ICON_TYPE_LOGOUT = 1164;
  BUILTIN_ICON_TYPE_MAILBOX = 1165;
  BUILTIN_ICON_TYPE_MCP = 1167;
  BUILTIN_ICON_TYPE_MEMORY = 1168;
  BUILTIN_ICON_TYPE_MENTION = 1169;
  BUILTIN_ICON_TYPE_MENU = 1170;
  BUILTIN_ICON_TYPE_MICROPHONE = 1171;
  BUILTIN_ICON_TYPE_MICROPHONE_FILLED = 1172;
  BUILTIN_ICON_TYPE_MICROPHONE_SLASH = 1173;
  BUILTIN_ICON_TYPE_MINUS = 1174;
  BUILTIN_ICON_TYPE_MOBILE_PHONE = 1175;
  BUILTIN_ICON_TYPE_MOON = 1176;
  BUILTIN_ICON_TYPE_MOON_FILLED = 1177;
  BUILTIN_ICON_TYPE_MOON_STARS = 1178;
  BUILTIN_ICON_TYPE_NOTE = 1179;
  BUILTIN_ICON_TYPE_NOTIFICATION_SLASH = 1181;
  BUILTIN_ICON_TYPE_ORGANIZATION = 1182;
  BUILTIN_ICON_TYPE_OWL = 1183;
  BUILTIN_ICON_TYPE_PALETTE = 1184;
  BUILTIN_ICON_TYPE_PALETTE_FILLED = 1185;
  BUILTIN_ICON_TYPE_PAPER_PLANE = 1186;
  BUILTIN_ICON_TYPE_PAUSE = 1187;
  BUILTIN_ICON_TYPE_PHONE = 1188;
  BUILTIN_ICON_TYPE_PIN = 1189;
  BUILTIN_ICON_TYPE_PIN_FILLED = 1190;
  BUILTIN_ICON_TYPE_PIN_SLASH = 1191;
  BUILTIN_ICON_TYPE_PLACEHOLDER = 1192;
  BUILTIN_ICON_TYPE_PLAY = 1193;
  BUILTIN_ICON_TYPE_PLAY_CIRCLE = 1194;
  BUILTIN_ICON_TYPE_PLAY_CIRCLE_FILLED = 1195;
  BUILTIN_ICON_TYPE_PLAY_FILLED = 1196;
  BUILTIN_ICON_TYPE_PLUGIN = 1197;
  BUILTIN_ICON_TYPE_PRESS = 1198;
  BUILTIN_ICON_TYPE_PRO = 1199;
  BUILTIN_ICON_TYPE_PROHIBIT = 1200;
  BUILTIN_ICON_TYPE_PROJECTS = 1201;
  BUILTIN_ICON_TYPE_PROJECTS_FILLED = 1202;
  BUILTIN_ICON_TYPE_PROJECTS_X = 1203;
  BUILTIN_ICON_TYPE_PROMPT = 1204;
  BUILTIN_ICON_TYPE_RECORDING = 1205;
  BUILTIN_ICON_TYPE_REORDER = 1207;
  BUILTIN_ICON_TYPE_RESEARCH = 1208;
  BUILTIN_ICON_TYPE_SCREENSHARE = 1209;
  BUILTIN_ICON_TYPE_SCROLL = 1210;
  BUILTIN_ICON_TYPE_SEARCH_CIRCLE = 1212;
  BUILTIN_ICON_TYPE_SELECT = 1213;
  BUILTIN_ICON_TYPE_SETTINGS = 1214;
  BUILTIN_ICON_TYPE_SHAPES = 1215;
  BUILTIN_ICON_TYPE_ARROW_BEND_UP_RIGHT = 1216;
  BUILTIN_ICON_TYPE_SHARE_ANDROID = 1217;
  BUILTIN_ICON_TYPE_SHIELD_SEARCH = 1219;
  BUILTIN_ICON_TYPE_SHUFFLE = 1220;
  BUILTIN_ICON_TYPE_SIDEBAR = 1221;
  BUILTIN_ICON_TYPE_SIDEBAR_CLOSE = 1222;
  BUILTIN_ICON_TYPE_SIDEBAR_OPEN = 1223;
  BUILTIN_ICON_TYPE_SIGNPOST = 1224;
  BUILTIN_ICON_TYPE_SLASH_SHORTCUT_COMMAND = 1225;
  BUILTIN_ICON_TYPE_SLIDES = 1226;
  BUILTIN_ICON_TYPE_SORT = 1227;
  BUILTIN_ICON_TYPE_SPEAKER = 1228;
  BUILTIN_ICON_TYPE_SPINNER = 1229;
  BUILTIN_ICON_TYPE_SPREADSHEET = 1230;
  BUILTIN_ICON_TYPE_STAR = 1231;
  BUILTIN_ICON_TYPE_STAR_FILLED = 1232;
  BUILTIN_ICON_TYPE_STAR_SLASH = 1233;
  BUILTIN_ICON_TYPE_STOP = 1234;
  BUILTIN_ICON_TYPE_STOP_CIRCLE = 1235;
  BUILTIN_ICON_TYPE_STOP_FILLED = 1236;
  BUILTIN_ICON_TYPE_STYLES = 1237;
  BUILTIN_ICON_TYPE_SUN = 1238;
  BUILTIN_ICON_TYPE_SUN_FILLED = 1239;
  BUILTIN_ICON_TYPE_SUN_HORIZON = 1240;
  BUILTIN_ICON_TYPE_TASKS = 1241;
  BUILTIN_ICON_TYPE_TEAM = 1242;
  BUILTIN_ICON_TYPE_TEMPERATURE = 1243;
  BUILTIN_ICON_TYPE_TEMPERATURE_SIMPLE = 1244;
  BUILTIN_ICON_TYPE_TEXT_AA = 1245;
  BUILTIN_ICON_TYPE_TEXT_BOLD = 1246;
  BUILTIN_ICON_TYPE_TEXT_ITALICS = 1247;
  BUILTIN_ICON_TYPE_TEXT_UNDERLINE = 1248;
  BUILTIN_ICON_TYPE_THUMBS_DOWN = 1249;
  BUILTIN_ICON_TYPE_THUMBS_DOWN_FILLED = 1250;
  BUILTIN_ICON_TYPE_THUMBS_UP = 1251;
  BUILTIN_ICON_TYPE_THUMBS_UP_FILLED = 1252;
  BUILTIN_ICON_TYPE_TIMER = 1253;
  BUILTIN_ICON_TYPE_TOGGLES = 1254;
  BUILTIN_ICON_TYPE_TOKEN = 1255;
  BUILTIN_ICON_TYPE_TOOL = 1256;
  BUILTIN_ICON_TYPE_TRASH = 1257;
  BUILTIN_ICON_TYPE_TRUST = 1258;
  BUILTIN_ICON_TYPE_USER = 1260;
  BUILTIN_ICON_TYPE_USER_CIRCLE = 1261;
  BUILTIN_ICON_TYPE_USERS = 1262;
  BUILTIN_ICON_TYPE_VERIFIED = 1263;
  BUILTIN_ICON_TYPE_VOICE = 1264;
  BUILTIN_ICON_TYPE_WARNING = 1265;
  BUILTIN_ICON_TYPE_WARNING_CIRCLE = 1266;
  BUILTIN_ICON_TYPE_WARNING_SHIELD = 1267;
  BUILTIN_ICON_TYPE_WORKSPACE = 1268;
  BUILTIN_ICON_TYPE_WRENCH_FILLED = 1270;
  BUILTIN_ICON_TYPE_X = 1271;
  BUILTIN_ICON_TYPE_X_CIRCLE = 1272;
  BUILTIN_ICON_TYPE_GIT_MERGE_QUEUE = 1273;
  BUILTIN_ICON_TYPE_ORBIT = 1274;
  BUILTIN_ICON_TYPE_SIDEBAR_RIGHT = 1275;
  BUILTIN_ICON_TYPE_BLUETOOTH = 1277;
  BUILTIN_ICON_TYPE_BLUETOOTH_SLASH = 1278;
  BUILTIN_ICON_TYPE_BOOKMARK = 1279;
  BUILTIN_ICON_TYPE_COMPUTER_CLASSIC = 1280;
  BUILTIN_ICON_TYPE_LINUX = 1281;
  BUILTIN_ICON_TYPE_WINDOWS = 1282;
  BUILTIN_ICON_TYPE_AGENT_SIMPLE = 1283;
  BUILTIN_ICON_TYPE_AGENTS_SIMPLE = 1284;
  BUILTIN_ICON_TYPE_ARROW_CLOCKWISE = 1285;
  BUILTIN_ICON_TYPE_ARROW_COUNTER_CLOCKWISE = 1286;
  BUILTIN_ICON_TYPE_MINIMIZE_BOTTOM_LEFT = 1287;
  BUILTIN_ICON_TYPE_MINIMIZE_BOTTOM_RIGHT = 1288;
  BUILTIN_ICON_TYPE_MINIMIZE_TOP_LEFT = 1289;
  BUILTIN_ICON_TYPE_MINIMIZE_TOP_RIGHT = 1290;
  BUILTIN_ICON_TYPE_EYE_FRAME = 1291;
  BUILTIN_ICON_TYPE_FRAME = 1292;
  BUILTIN_ICON_TYPE_HAMMER = 1293;
  BUILTIN_ICON_TYPE_HEALTH_CONNECT = 1294;
  BUILTIN_ICON_TYPE_HEART = 1295;
  BUILTIN_ICON_TYPE_SCALE = 1296;
  BUILTIN_ICON_TYPE_ARROW_DOWN_LEFT = 1297;
  BUILTIN_ICON_TYPE_ARROW_DOWN_RIGHT = 1298;
  BUILTIN_ICON_TYPE_ARROW_UP_LEFT = 1299;
  BUILTIN_ICON_TYPE_BANK = 1300;
  BUILTIN_ICON_TYPE_GOAL = 1301;
}
