// build-i18n.js (claude-ext-common)
// Bundles a folder's language tables (<lang>.js) into one generated all.js, so a manifest lists one
// file per table set instead of one per language. The per-language files stay the sources: edit those,
// then rebuild. check-i18n.js warns about a stale all.js, and mirror-debug.js --watch rebuilds on save.
//
//   node common/scripts/build-i18n.js [<dir>]...
//
// Paths are relative to the repo containing the submodule. Default: those of common/i18n, content/i18n
// (Toolbox) and i18n (Usage Tracker) that exist.
// Order inside all.js: en first, then the other languages alphabetically (each table only adds its
// own language, so the order changes nothing at runtime).
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..', '..');
const BUNDLE = 'all.js';
const isTable = (file) => /^[a-z]{2}(-[A-Z]{2})?\.js$/.test(file);
const defaultDirs = () => ['common/i18n', 'content/i18n', 'i18n'].map(d => path.join(root, d)).filter(fs.existsSync);

// The all.js content for dir, from its tables.
function bundle(dir) {
	const tables = fs.readdirSync(dir).filter(isTable).sort((a, b) => (a === 'en.js' ? -1 : b === 'en.js' ? 1 : a.localeCompare(b)));
	const header = `// GENERATED by common/scripts/build-i18n.js from ${tables.join(', ')}. Do not edit:\n`
		+ '// edit the per-language files, then run node common/scripts/build-i18n.js.\n';
	const parts = tables.map((file) => {
		const src = fs.readFileSync(path.join(dir, file), 'utf8').replace(/\r\n/g, '\n').trimEnd();
		return `// ---- ${file} ----\n${src}${src.endsWith(';') ? '' : ';'}\n`;
	});
	return header + '\n' + parts.join('\n');
}

const bundlePath = (dir) => path.join(dir, BUNDLE);
// The committed all.js as built, line endings aside (a checkout may have turned them into CRLF).
const current = (dir) => fs.existsSync(bundlePath(dir)) ? fs.readFileSync(bundlePath(dir), 'utf8').replace(/\r\n/g, '\n') : null;
const isStale = (dir) => current(dir) !== bundle(dir);

function build(dir) {
	const content = bundle(dir);
	const target = bundlePath(dir);
	if (current(dir) === content) return false;
	fs.writeFileSync(target, content);
	return true;
}

module.exports = { bundle, build, isStale, isTable, defaultDirs, BUNDLE };

if (require.main === module) {
	const args = process.argv.slice(2).map(d => path.resolve(root, d));
	for (const dir of args.length ? args : defaultDirs()) {
		console.log(`${path.relative(root, bundlePath(dir))}: ${build(dir) ? 'written' : 'up to date'}`);
	}
}
